apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-maintenance-page-deployment
spec:
  selector:
    matchLabels:
      app: docker-maintenance-page
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-maintenance-page
    spec:
      containers:
        - name: docker-maintenance-page
          image: timv5/docker-maintenance-page:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: docker-maintenance-page-service
spec:
  selector:
    app: docker-maintenance-page
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort